### ISSUE TITLE
Example image not working 

### ISSUE THREAD

**Issue by frostarun** [Huddle/Resemble.js#61]
When the example image is loaded , the result does not appear in chrome .. only manually added images show results ... 

And can you please show tutorial to build a page to load images automatically and showing the results while opening  the page ?

**Comment by jamescryer** [comment]
I think this is just because you have opened the index.html file locally and it's URL contains "file://".  You'll need to serve the html page with something like https://www.npmjs.com/package/http-server, ensuring that the html page is served from root e.g. http://localhost:8080, only then will the example images to load. This is because the example is using relative paths when constructing the XHR call.

I'm not going to create any tutorials. With a reasonable understanding of JavaScript, you should be able to create your own example page by understanding and changing the code in demoassets/main.js.

**Comment by frostarun** [comment]
Thank you !
